services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: <MYSQL-ROOT-PASSWORD>
      MARIADB_DATABASE: homeassistant
      MARIADB_USER: <HA-BDD-USER>
      MARIADB_PASSWORD: <HA-BDD-PASSWORD>
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - solar-panel

# Nextcloud: remove "depends_on" and "environment" if MariaDB is not needed.

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_PASSWORD: <MYSQL-ROOT-PASSWORD>
    volumes:
      - ./nextcloud:/var/www/html
    ports:
      - "8080:80"
    networks:
      - solar-panel

# Home Assistant: remove "depends_on" if MariaDB is not needed.
# To use MariaDB in Home Assistant, add this to configuration.yaml:
# recorder:
#   db_url: mysql://<HA-BDD-USER>:<HA-BDD-PASSWORD>@mariadb/homeassistant?charset=utf8mb4

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - ./homeassistant:/config
    ports:
      - "8123:8123"
    networks:
      - solar-panel

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:latest
    volumes:
      - /esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    environment:
      - ESPHOME_USERNAME=<YOUR-USERNAME>
      - ESPHOME_PASSWORD=<YOUR-PASSWORD>
      
volumes:
  portainer_data:

networks:
  solar-panel: